### ISSUE TITLE
Cannot run web apps with Spring 5

### ISSUE THREAD

**Issue by dsyer** [markfisher/spring-cloud-function#47]
There's a binary incompatibility. Maybe need to look at fixing it in Spring: https://jira.spring.io/browse/SPR-15410

<details>

```
Caused by: java.lang.NoSuchMethodError: org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler.<init>(Ljava/util/List;)V
    at org.springframework.cloud.function.web.flux.FluxReturnValueHandler.<init>(FluxReturnValueHandler.java:53) ~[classes/:na]
    at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration.fluxReturnValueHandler(ReactorAutoConfiguration.java:56) ~[classes/:na]
    at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$$EnhancerBySpringCGLIB$$e9d8b8ef.CGLIB$fluxReturnValueHandler$1(<generated>) ~[classes/:na]
    at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$$EnhancerBySpringCGLIB$$e9d8b8ef$$FastClassBySpringCGLIB$$64d3f2be.invoke(<generated>) ~[classes/:na]
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.0.BUILD-20170403.133901-52.jar:5.0.0.BUILD-SNAPSHOT]
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-5.0.0.BUILD-20170403.133901-52.jar:5.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$$EnhancerBySpringCGLIB$$e9d8b8ef.fluxReturnValueHandler(<generated>) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-5.0.0.BUILD-20170403.133901-52.jar:5.0.0.BUILD-SNAPSHOT]
    ... 47 common frames omitted
```

</details>

**Comment by dsyer** [comment]
That one is fixed. But now this one prevents function apps from working: https://jira.spring.io/browse/SPR-15478
